<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_kota extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('M_kota_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'm_kota/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'm_kota/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'm_kota/index.html';
            $config['first_url'] = base_url() . 'm_kota/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->M_kota_model->total_rows($q);
        $m_kota = $this->M_kota_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'm_kota_data' => $m_kota,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('m_kota/m_kota_list', $data);
    }

    public function read($id) 
    {
        $row = $this->M_kota_model->get_by_id($id);
        if ($row) {
            $data = array(
		'idkota' => $row->idkota,
		'idprovinsi' => $row->idprovinsi,
		'namakota' => $row->namakota,
	    );
            $this->load->view('m_kota/m_kota_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_kota'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('m_kota/create_action'),
	    'idkota' => set_value('idkota'),
	    'idprovinsi' => set_value('idprovinsi'),
	    'namakota' => set_value('namakota'),
	);
        $this->load->view('m_kota/m_kota_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'idprovinsi' => $this->input->post('idprovinsi',TRUE),
		'namakota' => $this->input->post('namakota',TRUE),
	    );

            $this->M_kota_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('m_kota'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->M_kota_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('m_kota/update_action'),
		'idkota' => set_value('idkota', $row->idkota),
		'idprovinsi' => set_value('idprovinsi', $row->idprovinsi),
		'namakota' => set_value('namakota', $row->namakota),
	    );
            $this->load->view('m_kota/m_kota_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_kota'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idkota', TRUE));
        } else {
            $data = array(
		'idprovinsi' => $this->input->post('idprovinsi',TRUE),
		'namakota' => $this->input->post('namakota',TRUE),
	    );

            $this->M_kota_model->update($this->input->post('idkota', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('m_kota'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->M_kota_model->get_by_id($id);

        if ($row) {
            $this->M_kota_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('m_kota'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('m_kota'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('idprovinsi', 'idprovinsi', 'trim|required');
	$this->form_validation->set_rules('namakota', 'namakota', 'trim|required');

	$this->form_validation->set_rules('idkota', 'idkota', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file M_kota.php */
/* Location: ./application/controllers/M_kota.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-06-27 08:54:03 */
/* http://harviacode.com */